### ISSUE TITLE
Increase major version

### ISSUE THREAD

**Issue by To1ne** [browse-kill-ring/browse-kill-ring#33]
Considering all the recent changes done (some of which are not backward compatible) I suggest we increase the major version number, so we'll get v2.0.0.

Information about the versioning scheme can be found at http://semver.org/.

**Comment by T-J-Teru** [comment]
I'm going to close this issue given that the version number has now been moved on.  Feel free to open a new issue, or reopen if there's more that needs to be done on this.

**Comment by To1ne** [comment]
Thanks, for doing this. I should have closed it a long time ago.
