### ISSUE TITLE
C-g does not quit browse-kill-ring

### ISSUE THREAD

**Issue by nsemrau** [browse-kill-ring/browse-kill-ring#58]
While `browse-kill-ring` correctly emits a `Quit` message in the minibuffer after pressing `C-g`, its window stays open and control remains with `browse-kill-ring`.
### Expected behavior

`C-g` closes `browse-kill-ring` and point returns to the window it was called from without inserting an entry from the kill-ring, analogous to pressing `q`.

**Comment by alezost** [comment]
It can be fixed by:
```elisp
(define-key browse-kill-ring-mode-map (kbd "C-g") 'browse-kill-ring-quit)
```

**Comment by T-J-Teru** [comment]
I've pushed commit b746d01c888262e81d76f8949869cf9e02759b6a to the master branch that make `C-g` quit browse-kill-ring, and also aborts edit mode.
