### ISSUE TITLE
Update kill-ring-yank-pointer when deleting kill-ring elements.

### ISSUE THREAD

**Issue by lawlist** [browse-kill-ring/browse-kill-ring#61]
In `browse-kill-ring-delete`, after `(setq kill-ring (delete target kill-ring))`, add:

     (catch 'done
      (mapc
        (lambda (x)
          (when (equal target (substring-no-properties x))
            (setq kill-ring-yank-pointer (delete target kill-ring-yank-pointer))
            (throw 'done nil)))
        kill-ring-yank-pointer))

**Comment by T-J-Teru** [comment]
This should be fixed by commit 5035bed.
